### ISSUE TITLE
Support change of retrieval addresses after adv is published

### ISSUE THREAD

**Issue by masih** [filecoin-project/index-provider#133]
Retrieval addresses are passed as constructor [arguments](https://github.com/filecoin-project/index-provider/blob/main/engine/engine.go#L96) to engine. They may change. Add mechanism to get those updated.

**Comment by masih** [comment]
Retrieval address is added to [each advertisement](https://github.com/filecoin-project/storetheindex/blob/main/api/v0/ingest/schema/schema.ipldsch#L29). This means if the retrevial address changes, the provider needs to:
1. detect that it has changed
    For example, when the engine is instantiated compare the address of the latest advertisement stored in datastore with the retrieval addresses given in the constructor.
2. On address change, walk the chain of published advertisements, calculate the delta of advertisement and republish them with the new address.

Notes on environmental factors:
1. Address does not change often
2. Advertisements are published per deal and number of deals are not super large.

So we don't need to be super efficient from get go.

Cc @willscott @aarshkshah1992

**Comment by gammazero** [comment]
Consider handling a change in retrieval address outside of advertisement.  if we expect these to change separately from the indexed data, then it seems like a huge burden to have to update all previously advertised index data for the provider to change its address.

That was originally how the indexer worked, and the main purpose behind the ability for a provider to register with an indexer.  It could (re)register at any time to update its address information.  The addresses were added to the advertisement because providers may not know what indexers to register with, so the advertisement was a good way to supply this to interested parties.

If we want to keep the addresses in the advertisements, without re-publishing all the advertisements on address change, then how about just publishing the address change in a new, but otherwise empty address.  The old advertisements will keep the old address, but indexers understand that only the most recently published address in the valid one for a provider.

**Comment by gammazero** [comment]
Creating a new advertisement with only the previous metadata will suffice to update the provider addresses.
