### ISSUE TITLE
if car supplier gets a carv1 it should save an index for it (as the dagstore would do)

### ISSUE THREAD

**Issue by willscott** [filecoin-project/index-provider#73]
currently a restart would need to re-scan the full carv1 if a retrieval or callback for it's index is ever encountered.

**Comment by masih** [comment]
Where would the index be stored? Are you thinking car supplier would modify the CARv1?

**Comment by willscott** [comment]
the reference provider maintains a data store with it's chain of advertisements. presumably in the same place?
probably safer to keep it as a detached index rather than modifying the source file directly.

**Comment by masih** [comment]
On a separate but related subject, I wonder if it makes sense to also store the deterministically ordered index, regardless of CAR version.

**Comment by gammazero** [comment]
The linksystem cache is already doing this, although not indefinitely. This is persisted across restarts now that the cache is backed by a data store, since PR #67.

The linked chunks for each advertisement are cached when the advertisement is published.  When the indexer asks for the advertised index data, the provider serves it from cache.  Being a cache, after some number of other advertisements are generated, older data may have moved out of the cache.  If an older advertisement is asked for again, it will be regenerated. ...unless the content has been removed (in which case the indexer should not ask for it).
